/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const STORE_LOGIN_DATA = 'STORE_LOGIN_DATA';
export const STORE_TOKEN = 'STORE_TOKEN';
export const STORE_EVENT = 'STORE_EVENT';
export const STORE_EVENT_TICKET = 'STORE_EVENT_TICKET';
export const STORE_EVENT_RAFFLE = 'STORE_EVENT_RAFFLE';
export const STORE_EVENT_FUND_A_NEED = 'STORE_EVENT_FUND_A_NEED';
export const STORE_EVENT_TICKET_DONATION = 'STORE_EVENT_TICKET_DONATION';
export const STORE_EVENT_AUCTION = 'STORE_EVENT_AUCTION';
export const STORE_ACTIVE_TAB = 'STORE_ACTIVE_TAB';
export const STORE_ORDER_DATA = 'STORE_ORDER_DATA';
export const GET_ORDERED_TICKER_DATA = 'GET_ORDERED_TICKER_DATA';
export const IS_VOLUNTEER = 'IS_VOLUNTEER';
export const IS_ITEMADDED = 'IS_ITEMADDED';
export const STORE_WHITE_LABLE_SETTING = 'STORE_WHITE_LABLE_SETTING';
export const STORE_HOST_DATA = 'STORE_HOST_DATA';
export const STORE_EVENT_CURRENCY = 'STORE_EVENT_CURRENCY';
export const STORE_CURRENCY_SYMBOLS = 'STORE_CURRENCY_SYMBOLS';
export const STORE_DESIGN_DATA = 'STORE_DESIGN_DATA';
export const LOCATION = 'LOCATION';
export const ITEMADD_SETTING = 'ITEMADD_SETTING';
